<?php
/**
 * EnvironmentlistInfoDayAndNight
 *
 * PHP version 5
 *
 * @category Class
 * @package  Psa\ConnectedCar
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Connected Car Development
 *
 * This is the first release of our connected car API. With this API you can access more than 89 signals in a car. This API is available on Peugeot, Citroën and DS cars.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: connectedcar@mpsa.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Psa\ConnectedCar\Model;

use \ArrayAccess;
use \Psa\ConnectedCar\ObjectSerializer;

/**
 * EnvironmentlistInfoDayAndNight Class Doc Comment
 *
 * @category Class
 * @package  Psa\ConnectedCar
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EnvironmentlistInfoDayAndNight implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'environmentlist_infoDayAndNight';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        '_1' => 'float',
        '_2' => 'float',
        '_3' => 'float',
        '_4' => 'float',
        '_5' => 'float',
        '_6' => 'float',
        '_7' => 'float',
        '_8' => 'float',
        '_9' => 'float',
        '_10' => 'float',
        '_11' => 'float',
        '_12' => 'float',
        '_13' => 'float',
        '_14' => 'float',
        '_15' => 'float',
        '_16' => 'float',
        '_17' => 'float',
        '_18' => 'float',
        '_19' => 'float',
        '_20' => 'float',
        '_21' => 'float',
        '_22' => 'float',
        '_23' => 'float',
        '_24' => 'float',
        '_25' => 'float',
        '_26' => 'float',
        '_27' => 'float',
        '_28' => 'float',
        '_29' => 'float',
        '_30' => 'float',
        '_31' => 'float',
        '_32' => 'float',
        '_33' => 'float',
        '_34' => 'float',
        '_35' => 'float',
        '_36' => 'float',
        '_37' => 'float',
        '_38' => 'float',
        '_39' => 'float',
        '_40' => 'float',
        '_41' => 'float',
        '_42' => 'float',
        '_43' => 'float',
        '_44' => 'float',
        '_45' => 'float',
        '_46' => 'float',
        '_47' => 'float',
        '_48' => 'float',
        '_49' => 'float',
        '_50' => 'float',
        '_51' => 'float',
        '_52' => 'float',
        '_53' => 'float',
        '_54' => 'float',
        '_55' => 'float',
        '_56' => 'float',
        '_57' => 'float',
        '_58' => 'float',
        '_59' => 'float',
        '_60' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        '_1' => null,
        '_2' => null,
        '_3' => null,
        '_4' => null,
        '_5' => null,
        '_6' => null,
        '_7' => null,
        '_8' => null,
        '_9' => null,
        '_10' => null,
        '_11' => null,
        '_12' => null,
        '_13' => null,
        '_14' => null,
        '_15' => null,
        '_16' => null,
        '_17' => null,
        '_18' => null,
        '_19' => null,
        '_20' => null,
        '_21' => null,
        '_22' => null,
        '_23' => null,
        '_24' => null,
        '_25' => null,
        '_26' => null,
        '_27' => null,
        '_28' => null,
        '_29' => null,
        '_30' => null,
        '_31' => null,
        '_32' => null,
        '_33' => null,
        '_34' => null,
        '_35' => null,
        '_36' => null,
        '_37' => null,
        '_38' => null,
        '_39' => null,
        '_40' => null,
        '_41' => null,
        '_42' => null,
        '_43' => null,
        '_44' => null,
        '_45' => null,
        '_46' => null,
        '_47' => null,
        '_48' => null,
        '_49' => null,
        '_50' => null,
        '_51' => null,
        '_52' => null,
        '_53' => null,
        '_54' => null,
        '_55' => null,
        '_56' => null,
        '_57' => null,
        '_58' => null,
        '_59' => null,
        '_60' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        '_1' => '1',
        '_2' => '2',
        '_3' => '3',
        '_4' => '4',
        '_5' => '5',
        '_6' => '6',
        '_7' => '7',
        '_8' => '8',
        '_9' => '9',
        '_10' => '10',
        '_11' => '11',
        '_12' => '12',
        '_13' => '13',
        '_14' => '14',
        '_15' => '15',
        '_16' => '16',
        '_17' => '17',
        '_18' => '18',
        '_19' => '19',
        '_20' => '20',
        '_21' => '21',
        '_22' => '22',
        '_23' => '23',
        '_24' => '24',
        '_25' => '25',
        '_26' => '26',
        '_27' => '27',
        '_28' => '28',
        '_29' => '29',
        '_30' => '30',
        '_31' => '31',
        '_32' => '32',
        '_33' => '33',
        '_34' => '34',
        '_35' => '35',
        '_36' => '36',
        '_37' => '37',
        '_38' => '38',
        '_39' => '39',
        '_40' => '40',
        '_41' => '41',
        '_42' => '42',
        '_43' => '43',
        '_44' => '44',
        '_45' => '45',
        '_46' => '46',
        '_47' => '47',
        '_48' => '48',
        '_49' => '49',
        '_50' => '50',
        '_51' => '51',
        '_52' => '52',
        '_53' => '53',
        '_54' => '54',
        '_55' => '55',
        '_56' => '56',
        '_57' => '57',
        '_58' => '58',
        '_59' => '59',
        '_60' => '60'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        '_1' => 'set1',
        '_2' => 'set2',
        '_3' => 'set3',
        '_4' => 'set4',
        '_5' => 'set5',
        '_6' => 'set6',
        '_7' => 'set7',
        '_8' => 'set8',
        '_9' => 'set9',
        '_10' => 'set10',
        '_11' => 'set11',
        '_12' => 'set12',
        '_13' => 'set13',
        '_14' => 'set14',
        '_15' => 'set15',
        '_16' => 'set16',
        '_17' => 'set17',
        '_18' => 'set18',
        '_19' => 'set19',
        '_20' => 'set20',
        '_21' => 'set21',
        '_22' => 'set22',
        '_23' => 'set23',
        '_24' => 'set24',
        '_25' => 'set25',
        '_26' => 'set26',
        '_27' => 'set27',
        '_28' => 'set28',
        '_29' => 'set29',
        '_30' => 'set30',
        '_31' => 'set31',
        '_32' => 'set32',
        '_33' => 'set33',
        '_34' => 'set34',
        '_35' => 'set35',
        '_36' => 'set36',
        '_37' => 'set37',
        '_38' => 'set38',
        '_39' => 'set39',
        '_40' => 'set40',
        '_41' => 'set41',
        '_42' => 'set42',
        '_43' => 'set43',
        '_44' => 'set44',
        '_45' => 'set45',
        '_46' => 'set46',
        '_47' => 'set47',
        '_48' => 'set48',
        '_49' => 'set49',
        '_50' => 'set50',
        '_51' => 'set51',
        '_52' => 'set52',
        '_53' => 'set53',
        '_54' => 'set54',
        '_55' => 'set55',
        '_56' => 'set56',
        '_57' => 'set57',
        '_58' => 'set58',
        '_59' => 'set59',
        '_60' => 'set60'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        '_1' => 'get1',
        '_2' => 'get2',
        '_3' => 'get3',
        '_4' => 'get4',
        '_5' => 'get5',
        '_6' => 'get6',
        '_7' => 'get7',
        '_8' => 'get8',
        '_9' => 'get9',
        '_10' => 'get10',
        '_11' => 'get11',
        '_12' => 'get12',
        '_13' => 'get13',
        '_14' => 'get14',
        '_15' => 'get15',
        '_16' => 'get16',
        '_17' => 'get17',
        '_18' => 'get18',
        '_19' => 'get19',
        '_20' => 'get20',
        '_21' => 'get21',
        '_22' => 'get22',
        '_23' => 'get23',
        '_24' => 'get24',
        '_25' => 'get25',
        '_26' => 'get26',
        '_27' => 'get27',
        '_28' => 'get28',
        '_29' => 'get29',
        '_30' => 'get30',
        '_31' => 'get31',
        '_32' => 'get32',
        '_33' => 'get33',
        '_34' => 'get34',
        '_35' => 'get35',
        '_36' => 'get36',
        '_37' => 'get37',
        '_38' => 'get38',
        '_39' => 'get39',
        '_40' => 'get40',
        '_41' => 'get41',
        '_42' => 'get42',
        '_43' => 'get43',
        '_44' => 'get44',
        '_45' => 'get45',
        '_46' => 'get46',
        '_47' => 'get47',
        '_48' => 'get48',
        '_49' => 'get49',
        '_50' => 'get50',
        '_51' => 'get51',
        '_52' => 'get52',
        '_53' => 'get53',
        '_54' => 'get54',
        '_55' => 'get55',
        '_56' => 'get56',
        '_57' => 'get57',
        '_58' => 'get58',
        '_59' => 'get59',
        '_60' => 'get60'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['_1'] = isset($data['_1']) ? $data['_1'] : null;
        $this->container['_2'] = isset($data['_2']) ? $data['_2'] : null;
        $this->container['_3'] = isset($data['_3']) ? $data['_3'] : null;
        $this->container['_4'] = isset($data['_4']) ? $data['_4'] : null;
        $this->container['_5'] = isset($data['_5']) ? $data['_5'] : null;
        $this->container['_6'] = isset($data['_6']) ? $data['_6'] : null;
        $this->container['_7'] = isset($data['_7']) ? $data['_7'] : null;
        $this->container['_8'] = isset($data['_8']) ? $data['_8'] : null;
        $this->container['_9'] = isset($data['_9']) ? $data['_9'] : null;
        $this->container['_10'] = isset($data['_10']) ? $data['_10'] : null;
        $this->container['_11'] = isset($data['_11']) ? $data['_11'] : null;
        $this->container['_12'] = isset($data['_12']) ? $data['_12'] : null;
        $this->container['_13'] = isset($data['_13']) ? $data['_13'] : null;
        $this->container['_14'] = isset($data['_14']) ? $data['_14'] : null;
        $this->container['_15'] = isset($data['_15']) ? $data['_15'] : null;
        $this->container['_16'] = isset($data['_16']) ? $data['_16'] : null;
        $this->container['_17'] = isset($data['_17']) ? $data['_17'] : null;
        $this->container['_18'] = isset($data['_18']) ? $data['_18'] : null;
        $this->container['_19'] = isset($data['_19']) ? $data['_19'] : null;
        $this->container['_20'] = isset($data['_20']) ? $data['_20'] : null;
        $this->container['_21'] = isset($data['_21']) ? $data['_21'] : null;
        $this->container['_22'] = isset($data['_22']) ? $data['_22'] : null;
        $this->container['_23'] = isset($data['_23']) ? $data['_23'] : null;
        $this->container['_24'] = isset($data['_24']) ? $data['_24'] : null;
        $this->container['_25'] = isset($data['_25']) ? $data['_25'] : null;
        $this->container['_26'] = isset($data['_26']) ? $data['_26'] : null;
        $this->container['_27'] = isset($data['_27']) ? $data['_27'] : null;
        $this->container['_28'] = isset($data['_28']) ? $data['_28'] : null;
        $this->container['_29'] = isset($data['_29']) ? $data['_29'] : null;
        $this->container['_30'] = isset($data['_30']) ? $data['_30'] : null;
        $this->container['_31'] = isset($data['_31']) ? $data['_31'] : null;
        $this->container['_32'] = isset($data['_32']) ? $data['_32'] : null;
        $this->container['_33'] = isset($data['_33']) ? $data['_33'] : null;
        $this->container['_34'] = isset($data['_34']) ? $data['_34'] : null;
        $this->container['_35'] = isset($data['_35']) ? $data['_35'] : null;
        $this->container['_36'] = isset($data['_36']) ? $data['_36'] : null;
        $this->container['_37'] = isset($data['_37']) ? $data['_37'] : null;
        $this->container['_38'] = isset($data['_38']) ? $data['_38'] : null;
        $this->container['_39'] = isset($data['_39']) ? $data['_39'] : null;
        $this->container['_40'] = isset($data['_40']) ? $data['_40'] : null;
        $this->container['_41'] = isset($data['_41']) ? $data['_41'] : null;
        $this->container['_42'] = isset($data['_42']) ? $data['_42'] : null;
        $this->container['_43'] = isset($data['_43']) ? $data['_43'] : null;
        $this->container['_44'] = isset($data['_44']) ? $data['_44'] : null;
        $this->container['_45'] = isset($data['_45']) ? $data['_45'] : null;
        $this->container['_46'] = isset($data['_46']) ? $data['_46'] : null;
        $this->container['_47'] = isset($data['_47']) ? $data['_47'] : null;
        $this->container['_48'] = isset($data['_48']) ? $data['_48'] : null;
        $this->container['_49'] = isset($data['_49']) ? $data['_49'] : null;
        $this->container['_50'] = isset($data['_50']) ? $data['_50'] : null;
        $this->container['_51'] = isset($data['_51']) ? $data['_51'] : null;
        $this->container['_52'] = isset($data['_52']) ? $data['_52'] : null;
        $this->container['_53'] = isset($data['_53']) ? $data['_53'] : null;
        $this->container['_54'] = isset($data['_54']) ? $data['_54'] : null;
        $this->container['_55'] = isset($data['_55']) ? $data['_55'] : null;
        $this->container['_56'] = isset($data['_56']) ? $data['_56'] : null;
        $this->container['_57'] = isset($data['_57']) ? $data['_57'] : null;
        $this->container['_58'] = isset($data['_58']) ? $data['_58'] : null;
        $this->container['_59'] = isset($data['_59']) ? $data['_59'] : null;
        $this->container['_60'] = isset($data['_60']) ? $data['_60'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets _1
     *
     * @return float
     */
    public function get1()
    {
        return $this->container['_1'];
    }

    /**
     * Sets _1
     *
     * @param float $_1 _1
     *
     * @return $this
     */
    public function set1($_1)
    {
        $this->container['_1'] = $_1;

        return $this;
    }

    /**
     * Gets _2
     *
     * @return float
     */
    public function get2()
    {
        return $this->container['_2'];
    }

    /**
     * Sets _2
     *
     * @param float $_2 _2
     *
     * @return $this
     */
    public function set2($_2)
    {
        $this->container['_2'] = $_2;

        return $this;
    }

    /**
     * Gets _3
     *
     * @return float
     */
    public function get3()
    {
        return $this->container['_3'];
    }

    /**
     * Sets _3
     *
     * @param float $_3 _3
     *
     * @return $this
     */
    public function set3($_3)
    {
        $this->container['_3'] = $_3;

        return $this;
    }

    /**
     * Gets _4
     *
     * @return float
     */
    public function get4()
    {
        return $this->container['_4'];
    }

    /**
     * Sets _4
     *
     * @param float $_4 _4
     *
     * @return $this
     */
    public function set4($_4)
    {
        $this->container['_4'] = $_4;

        return $this;
    }

    /**
     * Gets _5
     *
     * @return float
     */
    public function get5()
    {
        return $this->container['_5'];
    }

    /**
     * Sets _5
     *
     * @param float $_5 _5
     *
     * @return $this
     */
    public function set5($_5)
    {
        $this->container['_5'] = $_5;

        return $this;
    }

    /**
     * Gets _6
     *
     * @return float
     */
    public function get6()
    {
        return $this->container['_6'];
    }

    /**
     * Sets _6
     *
     * @param float $_6 _6
     *
     * @return $this
     */
    public function set6($_6)
    {
        $this->container['_6'] = $_6;

        return $this;
    }

    /**
     * Gets _7
     *
     * @return float
     */
    public function get7()
    {
        return $this->container['_7'];
    }

    /**
     * Sets _7
     *
     * @param float $_7 _7
     *
     * @return $this
     */
    public function set7($_7)
    {
        $this->container['_7'] = $_7;

        return $this;
    }

    /**
     * Gets _8
     *
     * @return float
     */
    public function get8()
    {
        return $this->container['_8'];
    }

    /**
     * Sets _8
     *
     * @param float $_8 _8
     *
     * @return $this
     */
    public function set8($_8)
    {
        $this->container['_8'] = $_8;

        return $this;
    }

    /**
     * Gets _9
     *
     * @return float
     */
    public function get9()
    {
        return $this->container['_9'];
    }

    /**
     * Sets _9
     *
     * @param float $_9 _9
     *
     * @return $this
     */
    public function set9($_9)
    {
        $this->container['_9'] = $_9;

        return $this;
    }

    /**
     * Gets _10
     *
     * @return float
     */
    public function get10()
    {
        return $this->container['_10'];
    }

    /**
     * Sets _10
     *
     * @param float $_10 _10
     *
     * @return $this
     */
    public function set10($_10)
    {
        $this->container['_10'] = $_10;

        return $this;
    }

    /**
     * Gets _11
     *
     * @return float
     */
    public function get11()
    {
        return $this->container['_11'];
    }

    /**
     * Sets _11
     *
     * @param float $_11 _11
     *
     * @return $this
     */
    public function set11($_11)
    {
        $this->container['_11'] = $_11;

        return $this;
    }

    /**
     * Gets _12
     *
     * @return float
     */
    public function get12()
    {
        return $this->container['_12'];
    }

    /**
     * Sets _12
     *
     * @param float $_12 _12
     *
     * @return $this
     */
    public function set12($_12)
    {
        $this->container['_12'] = $_12;

        return $this;
    }

    /**
     * Gets _13
     *
     * @return float
     */
    public function get13()
    {
        return $this->container['_13'];
    }

    /**
     * Sets _13
     *
     * @param float $_13 _13
     *
     * @return $this
     */
    public function set13($_13)
    {
        $this->container['_13'] = $_13;

        return $this;
    }

    /**
     * Gets _14
     *
     * @return float
     */
    public function get14()
    {
        return $this->container['_14'];
    }

    /**
     * Sets _14
     *
     * @param float $_14 _14
     *
     * @return $this
     */
    public function set14($_14)
    {
        $this->container['_14'] = $_14;

        return $this;
    }

    /**
     * Gets _15
     *
     * @return float
     */
    public function get15()
    {
        return $this->container['_15'];
    }

    /**
     * Sets _15
     *
     * @param float $_15 _15
     *
     * @return $this
     */
    public function set15($_15)
    {
        $this->container['_15'] = $_15;

        return $this;
    }

    /**
     * Gets _16
     *
     * @return float
     */
    public function get16()
    {
        return $this->container['_16'];
    }

    /**
     * Sets _16
     *
     * @param float $_16 _16
     *
     * @return $this
     */
    public function set16($_16)
    {
        $this->container['_16'] = $_16;

        return $this;
    }

    /**
     * Gets _17
     *
     * @return float
     */
    public function get17()
    {
        return $this->container['_17'];
    }

    /**
     * Sets _17
     *
     * @param float $_17 _17
     *
     * @return $this
     */
    public function set17($_17)
    {
        $this->container['_17'] = $_17;

        return $this;
    }

    /**
     * Gets _18
     *
     * @return float
     */
    public function get18()
    {
        return $this->container['_18'];
    }

    /**
     * Sets _18
     *
     * @param float $_18 _18
     *
     * @return $this
     */
    public function set18($_18)
    {
        $this->container['_18'] = $_18;

        return $this;
    }

    /**
     * Gets _19
     *
     * @return float
     */
    public function get19()
    {
        return $this->container['_19'];
    }

    /**
     * Sets _19
     *
     * @param float $_19 _19
     *
     * @return $this
     */
    public function set19($_19)
    {
        $this->container['_19'] = $_19;

        return $this;
    }

    /**
     * Gets _20
     *
     * @return float
     */
    public function get20()
    {
        return $this->container['_20'];
    }

    /**
     * Sets _20
     *
     * @param float $_20 _20
     *
     * @return $this
     */
    public function set20($_20)
    {
        $this->container['_20'] = $_20;

        return $this;
    }

    /**
     * Gets _21
     *
     * @return float
     */
    public function get21()
    {
        return $this->container['_21'];
    }

    /**
     * Sets _21
     *
     * @param float $_21 _21
     *
     * @return $this
     */
    public function set21($_21)
    {
        $this->container['_21'] = $_21;

        return $this;
    }

    /**
     * Gets _22
     *
     * @return float
     */
    public function get22()
    {
        return $this->container['_22'];
    }

    /**
     * Sets _22
     *
     * @param float $_22 _22
     *
     * @return $this
     */
    public function set22($_22)
    {
        $this->container['_22'] = $_22;

        return $this;
    }

    /**
     * Gets _23
     *
     * @return float
     */
    public function get23()
    {
        return $this->container['_23'];
    }

    /**
     * Sets _23
     *
     * @param float $_23 _23
     *
     * @return $this
     */
    public function set23($_23)
    {
        $this->container['_23'] = $_23;

        return $this;
    }

    /**
     * Gets _24
     *
     * @return float
     */
    public function get24()
    {
        return $this->container['_24'];
    }

    /**
     * Sets _24
     *
     * @param float $_24 _24
     *
     * @return $this
     */
    public function set24($_24)
    {
        $this->container['_24'] = $_24;

        return $this;
    }

    /**
     * Gets _25
     *
     * @return float
     */
    public function get25()
    {
        return $this->container['_25'];
    }

    /**
     * Sets _25
     *
     * @param float $_25 _25
     *
     * @return $this
     */
    public function set25($_25)
    {
        $this->container['_25'] = $_25;

        return $this;
    }

    /**
     * Gets _26
     *
     * @return float
     */
    public function get26()
    {
        return $this->container['_26'];
    }

    /**
     * Sets _26
     *
     * @param float $_26 _26
     *
     * @return $this
     */
    public function set26($_26)
    {
        $this->container['_26'] = $_26;

        return $this;
    }

    /**
     * Gets _27
     *
     * @return float
     */
    public function get27()
    {
        return $this->container['_27'];
    }

    /**
     * Sets _27
     *
     * @param float $_27 _27
     *
     * @return $this
     */
    public function set27($_27)
    {
        $this->container['_27'] = $_27;

        return $this;
    }

    /**
     * Gets _28
     *
     * @return float
     */
    public function get28()
    {
        return $this->container['_28'];
    }

    /**
     * Sets _28
     *
     * @param float $_28 _28
     *
     * @return $this
     */
    public function set28($_28)
    {
        $this->container['_28'] = $_28;

        return $this;
    }

    /**
     * Gets _29
     *
     * @return float
     */
    public function get29()
    {
        return $this->container['_29'];
    }

    /**
     * Sets _29
     *
     * @param float $_29 _29
     *
     * @return $this
     */
    public function set29($_29)
    {
        $this->container['_29'] = $_29;

        return $this;
    }

    /**
     * Gets _30
     *
     * @return float
     */
    public function get30()
    {
        return $this->container['_30'];
    }

    /**
     * Sets _30
     *
     * @param float $_30 _30
     *
     * @return $this
     */
    public function set30($_30)
    {
        $this->container['_30'] = $_30;

        return $this;
    }

    /**
     * Gets _31
     *
     * @return float
     */
    public function get31()
    {
        return $this->container['_31'];
    }

    /**
     * Sets _31
     *
     * @param float $_31 _31
     *
     * @return $this
     */
    public function set31($_31)
    {
        $this->container['_31'] = $_31;

        return $this;
    }

    /**
     * Gets _32
     *
     * @return float
     */
    public function get32()
    {
        return $this->container['_32'];
    }

    /**
     * Sets _32
     *
     * @param float $_32 _32
     *
     * @return $this
     */
    public function set32($_32)
    {
        $this->container['_32'] = $_32;

        return $this;
    }

    /**
     * Gets _33
     *
     * @return float
     */
    public function get33()
    {
        return $this->container['_33'];
    }

    /**
     * Sets _33
     *
     * @param float $_33 _33
     *
     * @return $this
     */
    public function set33($_33)
    {
        $this->container['_33'] = $_33;

        return $this;
    }

    /**
     * Gets _34
     *
     * @return float
     */
    public function get34()
    {
        return $this->container['_34'];
    }

    /**
     * Sets _34
     *
     * @param float $_34 _34
     *
     * @return $this
     */
    public function set34($_34)
    {
        $this->container['_34'] = $_34;

        return $this;
    }

    /**
     * Gets _35
     *
     * @return float
     */
    public function get35()
    {
        return $this->container['_35'];
    }

    /**
     * Sets _35
     *
     * @param float $_35 _35
     *
     * @return $this
     */
    public function set35($_35)
    {
        $this->container['_35'] = $_35;

        return $this;
    }

    /**
     * Gets _36
     *
     * @return float
     */
    public function get36()
    {
        return $this->container['_36'];
    }

    /**
     * Sets _36
     *
     * @param float $_36 _36
     *
     * @return $this
     */
    public function set36($_36)
    {
        $this->container['_36'] = $_36;

        return $this;
    }

    /**
     * Gets _37
     *
     * @return float
     */
    public function get37()
    {
        return $this->container['_37'];
    }

    /**
     * Sets _37
     *
     * @param float $_37 _37
     *
     * @return $this
     */
    public function set37($_37)
    {
        $this->container['_37'] = $_37;

        return $this;
    }

    /**
     * Gets _38
     *
     * @return float
     */
    public function get38()
    {
        return $this->container['_38'];
    }

    /**
     * Sets _38
     *
     * @param float $_38 _38
     *
     * @return $this
     */
    public function set38($_38)
    {
        $this->container['_38'] = $_38;

        return $this;
    }

    /**
     * Gets _39
     *
     * @return float
     */
    public function get39()
    {
        return $this->container['_39'];
    }

    /**
     * Sets _39
     *
     * @param float $_39 _39
     *
     * @return $this
     */
    public function set39($_39)
    {
        $this->container['_39'] = $_39;

        return $this;
    }

    /**
     * Gets _40
     *
     * @return float
     */
    public function get40()
    {
        return $this->container['_40'];
    }

    /**
     * Sets _40
     *
     * @param float $_40 _40
     *
     * @return $this
     */
    public function set40($_40)
    {
        $this->container['_40'] = $_40;

        return $this;
    }

    /**
     * Gets _41
     *
     * @return float
     */
    public function get41()
    {
        return $this->container['_41'];
    }

    /**
     * Sets _41
     *
     * @param float $_41 _41
     *
     * @return $this
     */
    public function set41($_41)
    {
        $this->container['_41'] = $_41;

        return $this;
    }

    /**
     * Gets _42
     *
     * @return float
     */
    public function get42()
    {
        return $this->container['_42'];
    }

    /**
     * Sets _42
     *
     * @param float $_42 _42
     *
     * @return $this
     */
    public function set42($_42)
    {
        $this->container['_42'] = $_42;

        return $this;
    }

    /**
     * Gets _43
     *
     * @return float
     */
    public function get43()
    {
        return $this->container['_43'];
    }

    /**
     * Sets _43
     *
     * @param float $_43 _43
     *
     * @return $this
     */
    public function set43($_43)
    {
        $this->container['_43'] = $_43;

        return $this;
    }

    /**
     * Gets _44
     *
     * @return float
     */
    public function get44()
    {
        return $this->container['_44'];
    }

    /**
     * Sets _44
     *
     * @param float $_44 _44
     *
     * @return $this
     */
    public function set44($_44)
    {
        $this->container['_44'] = $_44;

        return $this;
    }

    /**
     * Gets _45
     *
     * @return float
     */
    public function get45()
    {
        return $this->container['_45'];
    }

    /**
     * Sets _45
     *
     * @param float $_45 _45
     *
     * @return $this
     */
    public function set45($_45)
    {
        $this->container['_45'] = $_45;

        return $this;
    }

    /**
     * Gets _46
     *
     * @return float
     */
    public function get46()
    {
        return $this->container['_46'];
    }

    /**
     * Sets _46
     *
     * @param float $_46 _46
     *
     * @return $this
     */
    public function set46($_46)
    {
        $this->container['_46'] = $_46;

        return $this;
    }

    /**
     * Gets _47
     *
     * @return float
     */
    public function get47()
    {
        return $this->container['_47'];
    }

    /**
     * Sets _47
     *
     * @param float $_47 _47
     *
     * @return $this
     */
    public function set47($_47)
    {
        $this->container['_47'] = $_47;

        return $this;
    }

    /**
     * Gets _48
     *
     * @return float
     */
    public function get48()
    {
        return $this->container['_48'];
    }

    /**
     * Sets _48
     *
     * @param float $_48 _48
     *
     * @return $this
     */
    public function set48($_48)
    {
        $this->container['_48'] = $_48;

        return $this;
    }

    /**
     * Gets _49
     *
     * @return float
     */
    public function get49()
    {
        return $this->container['_49'];
    }

    /**
     * Sets _49
     *
     * @param float $_49 _49
     *
     * @return $this
     */
    public function set49($_49)
    {
        $this->container['_49'] = $_49;

        return $this;
    }

    /**
     * Gets _50
     *
     * @return float
     */
    public function get50()
    {
        return $this->container['_50'];
    }

    /**
     * Sets _50
     *
     * @param float $_50 _50
     *
     * @return $this
     */
    public function set50($_50)
    {
        $this->container['_50'] = $_50;

        return $this;
    }

    /**
     * Gets _51
     *
     * @return float
     */
    public function get51()
    {
        return $this->container['_51'];
    }

    /**
     * Sets _51
     *
     * @param float $_51 _51
     *
     * @return $this
     */
    public function set51($_51)
    {
        $this->container['_51'] = $_51;

        return $this;
    }

    /**
     * Gets _52
     *
     * @return float
     */
    public function get52()
    {
        return $this->container['_52'];
    }

    /**
     * Sets _52
     *
     * @param float $_52 _52
     *
     * @return $this
     */
    public function set52($_52)
    {
        $this->container['_52'] = $_52;

        return $this;
    }

    /**
     * Gets _53
     *
     * @return float
     */
    public function get53()
    {
        return $this->container['_53'];
    }

    /**
     * Sets _53
     *
     * @param float $_53 _53
     *
     * @return $this
     */
    public function set53($_53)
    {
        $this->container['_53'] = $_53;

        return $this;
    }

    /**
     * Gets _54
     *
     * @return float
     */
    public function get54()
    {
        return $this->container['_54'];
    }

    /**
     * Sets _54
     *
     * @param float $_54 _54
     *
     * @return $this
     */
    public function set54($_54)
    {
        $this->container['_54'] = $_54;

        return $this;
    }

    /**
     * Gets _55
     *
     * @return float
     */
    public function get55()
    {
        return $this->container['_55'];
    }

    /**
     * Sets _55
     *
     * @param float $_55 _55
     *
     * @return $this
     */
    public function set55($_55)
    {
        $this->container['_55'] = $_55;

        return $this;
    }

    /**
     * Gets _56
     *
     * @return float
     */
    public function get56()
    {
        return $this->container['_56'];
    }

    /**
     * Sets _56
     *
     * @param float $_56 _56
     *
     * @return $this
     */
    public function set56($_56)
    {
        $this->container['_56'] = $_56;

        return $this;
    }

    /**
     * Gets _57
     *
     * @return float
     */
    public function get57()
    {
        return $this->container['_57'];
    }

    /**
     * Sets _57
     *
     * @param float $_57 _57
     *
     * @return $this
     */
    public function set57($_57)
    {
        $this->container['_57'] = $_57;

        return $this;
    }

    /**
     * Gets _58
     *
     * @return float
     */
    public function get58()
    {
        return $this->container['_58'];
    }

    /**
     * Sets _58
     *
     * @param float $_58 _58
     *
     * @return $this
     */
    public function set58($_58)
    {
        $this->container['_58'] = $_58;

        return $this;
    }

    /**
     * Gets _59
     *
     * @return float
     */
    public function get59()
    {
        return $this->container['_59'];
    }

    /**
     * Sets _59
     *
     * @param float $_59 _59
     *
     * @return $this
     */
    public function set59($_59)
    {
        $this->container['_59'] = $_59;

        return $this;
    }

    /**
     * Gets _60
     *
     * @return float
     */
    public function get60()
    {
        return $this->container['_60'];
    }

    /**
     * Sets _60
     *
     * @param float $_60 _60
     *
     * @return $this
     */
    public function set60($_60)
    {
        $this->container['_60'] = $_60;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


