<?php
/**
 * InlineResponse2006Fuel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Psa\ConnectedCar
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Connected Car Development
 *
 * This is the first release of our connected car API. With this API you can access more than 89 signals in a car. This API is available on Peugeot, Citroën and DS cars.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: connectedcar@mpsa.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Psa\ConnectedCar\Model;

use \ArrayAccess;
use \Psa\ConnectedCar\ObjectSerializer;

/**
 * InlineResponse2006Fuel Class Doc Comment
 *
 * @category Class
 * @package  Psa\ConnectedCar
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2006Fuel implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'inline_response_200_6_fuel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'fuelTankAlerte' => 'float',
        'fuelTankAlerteLabel' => '\Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel',
        'residualAutonomy' => 'float',
        'residualAutonomyLabel' => '\Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel',
        'fuelTotalConsumption' => 'float',
        'fuelTotalConsumptionLabel' => '\Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel',
        'fuelLevel' => 'float',
        'fuelLevelLabel' => '\Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel',
        'fuelTankCapacity' => 'float',
        'fuelTankCapacityLabel' => '\Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel',
        'instFuelConsumption10' => 'float',
        'instFuelConsumption10Label' => '\Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel',
        'instFuelConsumption20' => 'float',
        'instFuelConsumption20Label' => '\Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel',
        'instFuelConsumption30' => 'float',
        'instFuelConsumption30Label' => '\Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel',
        'instFuelConsumption40' => 'float',
        'instFuelConsumption40Label' => '\Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel',
        'instFuelConsumption50' => 'float',
        'instFuelConsumption50Label' => '\Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel',
        'instFuelConsumption60' => 'float',
        'instFuelConsumption60Label' => '\Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'fuelTankAlerte' => null,
        'fuelTankAlerteLabel' => null,
        'residualAutonomy' => null,
        'residualAutonomyLabel' => null,
        'fuelTotalConsumption' => null,
        'fuelTotalConsumptionLabel' => null,
        'fuelLevel' => null,
        'fuelLevelLabel' => null,
        'fuelTankCapacity' => null,
        'fuelTankCapacityLabel' => null,
        'instFuelConsumption10' => null,
        'instFuelConsumption10Label' => null,
        'instFuelConsumption20' => null,
        'instFuelConsumption20Label' => null,
        'instFuelConsumption30' => null,
        'instFuelConsumption30Label' => null,
        'instFuelConsumption40' => null,
        'instFuelConsumption40Label' => null,
        'instFuelConsumption50' => null,
        'instFuelConsumption50Label' => null,
        'instFuelConsumption60' => null,
        'instFuelConsumption60Label' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fuelTankAlerte' => 'fuelTankAlerte',
        'fuelTankAlerteLabel' => 'fuelTankAlerteLabel',
        'residualAutonomy' => 'residualAutonomy',
        'residualAutonomyLabel' => 'residualAutonomyLabel',
        'fuelTotalConsumption' => 'fuelTotalConsumption',
        'fuelTotalConsumptionLabel' => 'fuelTotalConsumptionLabel',
        'fuelLevel' => 'fuelLevel',
        'fuelLevelLabel' => 'fuelLevelLabel',
        'fuelTankCapacity' => 'fuelTankCapacity',
        'fuelTankCapacityLabel' => 'fuelTankCapacityLabel',
        'instFuelConsumption10' => 'instFuelConsumption10',
        'instFuelConsumption10Label' => 'instFuelConsumption10Label',
        'instFuelConsumption20' => 'instFuelConsumption20',
        'instFuelConsumption20Label' => 'instFuelConsumption20Label',
        'instFuelConsumption30' => 'instFuelConsumption30',
        'instFuelConsumption30Label' => 'instFuelConsumption30Label',
        'instFuelConsumption40' => 'instFuelConsumption40',
        'instFuelConsumption40Label' => 'instFuelConsumption40Label',
        'instFuelConsumption50' => 'instFuelConsumption50',
        'instFuelConsumption50Label' => 'instFuelConsumption50Label',
        'instFuelConsumption60' => 'instFuelConsumption60',
        'instFuelConsumption60Label' => 'instFuelConsumption60Label'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fuelTankAlerte' => 'setFuelTankAlerte',
        'fuelTankAlerteLabel' => 'setFuelTankAlerteLabel',
        'residualAutonomy' => 'setResidualAutonomy',
        'residualAutonomyLabel' => 'setResidualAutonomyLabel',
        'fuelTotalConsumption' => 'setFuelTotalConsumption',
        'fuelTotalConsumptionLabel' => 'setFuelTotalConsumptionLabel',
        'fuelLevel' => 'setFuelLevel',
        'fuelLevelLabel' => 'setFuelLevelLabel',
        'fuelTankCapacity' => 'setFuelTankCapacity',
        'fuelTankCapacityLabel' => 'setFuelTankCapacityLabel',
        'instFuelConsumption10' => 'setInstFuelConsumption10',
        'instFuelConsumption10Label' => 'setInstFuelConsumption10Label',
        'instFuelConsumption20' => 'setInstFuelConsumption20',
        'instFuelConsumption20Label' => 'setInstFuelConsumption20Label',
        'instFuelConsumption30' => 'setInstFuelConsumption30',
        'instFuelConsumption30Label' => 'setInstFuelConsumption30Label',
        'instFuelConsumption40' => 'setInstFuelConsumption40',
        'instFuelConsumption40Label' => 'setInstFuelConsumption40Label',
        'instFuelConsumption50' => 'setInstFuelConsumption50',
        'instFuelConsumption50Label' => 'setInstFuelConsumption50Label',
        'instFuelConsumption60' => 'setInstFuelConsumption60',
        'instFuelConsumption60Label' => 'setInstFuelConsumption60Label'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fuelTankAlerte' => 'getFuelTankAlerte',
        'fuelTankAlerteLabel' => 'getFuelTankAlerteLabel',
        'residualAutonomy' => 'getResidualAutonomy',
        'residualAutonomyLabel' => 'getResidualAutonomyLabel',
        'fuelTotalConsumption' => 'getFuelTotalConsumption',
        'fuelTotalConsumptionLabel' => 'getFuelTotalConsumptionLabel',
        'fuelLevel' => 'getFuelLevel',
        'fuelLevelLabel' => 'getFuelLevelLabel',
        'fuelTankCapacity' => 'getFuelTankCapacity',
        'fuelTankCapacityLabel' => 'getFuelTankCapacityLabel',
        'instFuelConsumption10' => 'getInstFuelConsumption10',
        'instFuelConsumption10Label' => 'getInstFuelConsumption10Label',
        'instFuelConsumption20' => 'getInstFuelConsumption20',
        'instFuelConsumption20Label' => 'getInstFuelConsumption20Label',
        'instFuelConsumption30' => 'getInstFuelConsumption30',
        'instFuelConsumption30Label' => 'getInstFuelConsumption30Label',
        'instFuelConsumption40' => 'getInstFuelConsumption40',
        'instFuelConsumption40Label' => 'getInstFuelConsumption40Label',
        'instFuelConsumption50' => 'getInstFuelConsumption50',
        'instFuelConsumption50Label' => 'getInstFuelConsumption50Label',
        'instFuelConsumption60' => 'getInstFuelConsumption60',
        'instFuelConsumption60Label' => 'getInstFuelConsumption60Label'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['fuelTankAlerte'] = isset($data['fuelTankAlerte']) ? $data['fuelTankAlerte'] : null;
        $this->container['fuelTankAlerteLabel'] = isset($data['fuelTankAlerteLabel']) ? $data['fuelTankAlerteLabel'] : null;
        $this->container['residualAutonomy'] = isset($data['residualAutonomy']) ? $data['residualAutonomy'] : null;
        $this->container['residualAutonomyLabel'] = isset($data['residualAutonomyLabel']) ? $data['residualAutonomyLabel'] : null;
        $this->container['fuelTotalConsumption'] = isset($data['fuelTotalConsumption']) ? $data['fuelTotalConsumption'] : null;
        $this->container['fuelTotalConsumptionLabel'] = isset($data['fuelTotalConsumptionLabel']) ? $data['fuelTotalConsumptionLabel'] : null;
        $this->container['fuelLevel'] = isset($data['fuelLevel']) ? $data['fuelLevel'] : null;
        $this->container['fuelLevelLabel'] = isset($data['fuelLevelLabel']) ? $data['fuelLevelLabel'] : null;
        $this->container['fuelTankCapacity'] = isset($data['fuelTankCapacity']) ? $data['fuelTankCapacity'] : null;
        $this->container['fuelTankCapacityLabel'] = isset($data['fuelTankCapacityLabel']) ? $data['fuelTankCapacityLabel'] : null;
        $this->container['instFuelConsumption10'] = isset($data['instFuelConsumption10']) ? $data['instFuelConsumption10'] : null;
        $this->container['instFuelConsumption10Label'] = isset($data['instFuelConsumption10Label']) ? $data['instFuelConsumption10Label'] : null;
        $this->container['instFuelConsumption20'] = isset($data['instFuelConsumption20']) ? $data['instFuelConsumption20'] : null;
        $this->container['instFuelConsumption20Label'] = isset($data['instFuelConsumption20Label']) ? $data['instFuelConsumption20Label'] : null;
        $this->container['instFuelConsumption30'] = isset($data['instFuelConsumption30']) ? $data['instFuelConsumption30'] : null;
        $this->container['instFuelConsumption30Label'] = isset($data['instFuelConsumption30Label']) ? $data['instFuelConsumption30Label'] : null;
        $this->container['instFuelConsumption40'] = isset($data['instFuelConsumption40']) ? $data['instFuelConsumption40'] : null;
        $this->container['instFuelConsumption40Label'] = isset($data['instFuelConsumption40Label']) ? $data['instFuelConsumption40Label'] : null;
        $this->container['instFuelConsumption50'] = isset($data['instFuelConsumption50']) ? $data['instFuelConsumption50'] : null;
        $this->container['instFuelConsumption50Label'] = isset($data['instFuelConsumption50Label']) ? $data['instFuelConsumption50Label'] : null;
        $this->container['instFuelConsumption60'] = isset($data['instFuelConsumption60']) ? $data['instFuelConsumption60'] : null;
        $this->container['instFuelConsumption60Label'] = isset($data['instFuelConsumption60Label']) ? $data['instFuelConsumption60Label'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fuelTankAlerte
     *
     * @return float
     */
    public function getFuelTankAlerte()
    {
        return $this->container['fuelTankAlerte'];
    }

    /**
     * Sets fuelTankAlerte
     *
     * @param float $fuelTankAlerte fuelTankAlerte
     *
     * @return $this
     */
    public function setFuelTankAlerte($fuelTankAlerte)
    {
        $this->container['fuelTankAlerte'] = $fuelTankAlerte;

        return $this;
    }

    /**
     * Gets fuelTankAlerteLabel
     *
     * @return \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel
     */
    public function getFuelTankAlerteLabel()
    {
        return $this->container['fuelTankAlerteLabel'];
    }

    /**
     * Sets fuelTankAlerteLabel
     *
     * @param \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel $fuelTankAlerteLabel fuelTankAlerteLabel
     *
     * @return $this
     */
    public function setFuelTankAlerteLabel($fuelTankAlerteLabel)
    {
        $this->container['fuelTankAlerteLabel'] = $fuelTankAlerteLabel;

        return $this;
    }

    /**
     * Gets residualAutonomy
     *
     * @return float
     */
    public function getResidualAutonomy()
    {
        return $this->container['residualAutonomy'];
    }

    /**
     * Sets residualAutonomy
     *
     * @param float $residualAutonomy residualAutonomy
     *
     * @return $this
     */
    public function setResidualAutonomy($residualAutonomy)
    {
        $this->container['residualAutonomy'] = $residualAutonomy;

        return $this;
    }

    /**
     * Gets residualAutonomyLabel
     *
     * @return \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel
     */
    public function getResidualAutonomyLabel()
    {
        return $this->container['residualAutonomyLabel'];
    }

    /**
     * Sets residualAutonomyLabel
     *
     * @param \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel $residualAutonomyLabel residualAutonomyLabel
     *
     * @return $this
     */
    public function setResidualAutonomyLabel($residualAutonomyLabel)
    {
        $this->container['residualAutonomyLabel'] = $residualAutonomyLabel;

        return $this;
    }

    /**
     * Gets fuelTotalConsumption
     *
     * @return float
     */
    public function getFuelTotalConsumption()
    {
        return $this->container['fuelTotalConsumption'];
    }

    /**
     * Sets fuelTotalConsumption
     *
     * @param float $fuelTotalConsumption fuelTotalConsumption
     *
     * @return $this
     */
    public function setFuelTotalConsumption($fuelTotalConsumption)
    {
        $this->container['fuelTotalConsumption'] = $fuelTotalConsumption;

        return $this;
    }

    /**
     * Gets fuelTotalConsumptionLabel
     *
     * @return \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel
     */
    public function getFuelTotalConsumptionLabel()
    {
        return $this->container['fuelTotalConsumptionLabel'];
    }

    /**
     * Sets fuelTotalConsumptionLabel
     *
     * @param \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel $fuelTotalConsumptionLabel fuelTotalConsumptionLabel
     *
     * @return $this
     */
    public function setFuelTotalConsumptionLabel($fuelTotalConsumptionLabel)
    {
        $this->container['fuelTotalConsumptionLabel'] = $fuelTotalConsumptionLabel;

        return $this;
    }

    /**
     * Gets fuelLevel
     *
     * @return float
     */
    public function getFuelLevel()
    {
        return $this->container['fuelLevel'];
    }

    /**
     * Sets fuelLevel
     *
     * @param float $fuelLevel fuelLevel
     *
     * @return $this
     */
    public function setFuelLevel($fuelLevel)
    {
        $this->container['fuelLevel'] = $fuelLevel;

        return $this;
    }

    /**
     * Gets fuelLevelLabel
     *
     * @return \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel
     */
    public function getFuelLevelLabel()
    {
        return $this->container['fuelLevelLabel'];
    }

    /**
     * Sets fuelLevelLabel
     *
     * @param \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel $fuelLevelLabel fuelLevelLabel
     *
     * @return $this
     */
    public function setFuelLevelLabel($fuelLevelLabel)
    {
        $this->container['fuelLevelLabel'] = $fuelLevelLabel;

        return $this;
    }

    /**
     * Gets fuelTankCapacity
     *
     * @return float
     */
    public function getFuelTankCapacity()
    {
        return $this->container['fuelTankCapacity'];
    }

    /**
     * Sets fuelTankCapacity
     *
     * @param float $fuelTankCapacity fuelTankCapacity
     *
     * @return $this
     */
    public function setFuelTankCapacity($fuelTankCapacity)
    {
        $this->container['fuelTankCapacity'] = $fuelTankCapacity;

        return $this;
    }

    /**
     * Gets fuelTankCapacityLabel
     *
     * @return \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel
     */
    public function getFuelTankCapacityLabel()
    {
        return $this->container['fuelTankCapacityLabel'];
    }

    /**
     * Sets fuelTankCapacityLabel
     *
     * @param \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel $fuelTankCapacityLabel fuelTankCapacityLabel
     *
     * @return $this
     */
    public function setFuelTankCapacityLabel($fuelTankCapacityLabel)
    {
        $this->container['fuelTankCapacityLabel'] = $fuelTankCapacityLabel;

        return $this;
    }

    /**
     * Gets instFuelConsumption10
     *
     * @return float
     */
    public function getInstFuelConsumption10()
    {
        return $this->container['instFuelConsumption10'];
    }

    /**
     * Sets instFuelConsumption10
     *
     * @param float $instFuelConsumption10 instFuelConsumption10
     *
     * @return $this
     */
    public function setInstFuelConsumption10($instFuelConsumption10)
    {
        $this->container['instFuelConsumption10'] = $instFuelConsumption10;

        return $this;
    }

    /**
     * Gets instFuelConsumption10Label
     *
     * @return \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel
     */
    public function getInstFuelConsumption10Label()
    {
        return $this->container['instFuelConsumption10Label'];
    }

    /**
     * Sets instFuelConsumption10Label
     *
     * @param \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel $instFuelConsumption10Label instFuelConsumption10Label
     *
     * @return $this
     */
    public function setInstFuelConsumption10Label($instFuelConsumption10Label)
    {
        $this->container['instFuelConsumption10Label'] = $instFuelConsumption10Label;

        return $this;
    }

    /**
     * Gets instFuelConsumption20
     *
     * @return float
     */
    public function getInstFuelConsumption20()
    {
        return $this->container['instFuelConsumption20'];
    }

    /**
     * Sets instFuelConsumption20
     *
     * @param float $instFuelConsumption20 instFuelConsumption20
     *
     * @return $this
     */
    public function setInstFuelConsumption20($instFuelConsumption20)
    {
        $this->container['instFuelConsumption20'] = $instFuelConsumption20;

        return $this;
    }

    /**
     * Gets instFuelConsumption20Label
     *
     * @return \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel
     */
    public function getInstFuelConsumption20Label()
    {
        return $this->container['instFuelConsumption20Label'];
    }

    /**
     * Sets instFuelConsumption20Label
     *
     * @param \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel $instFuelConsumption20Label instFuelConsumption20Label
     *
     * @return $this
     */
    public function setInstFuelConsumption20Label($instFuelConsumption20Label)
    {
        $this->container['instFuelConsumption20Label'] = $instFuelConsumption20Label;

        return $this;
    }

    /**
     * Gets instFuelConsumption30
     *
     * @return float
     */
    public function getInstFuelConsumption30()
    {
        return $this->container['instFuelConsumption30'];
    }

    /**
     * Sets instFuelConsumption30
     *
     * @param float $instFuelConsumption30 instFuelConsumption30
     *
     * @return $this
     */
    public function setInstFuelConsumption30($instFuelConsumption30)
    {
        $this->container['instFuelConsumption30'] = $instFuelConsumption30;

        return $this;
    }

    /**
     * Gets instFuelConsumption30Label
     *
     * @return \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel
     */
    public function getInstFuelConsumption30Label()
    {
        return $this->container['instFuelConsumption30Label'];
    }

    /**
     * Sets instFuelConsumption30Label
     *
     * @param \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel $instFuelConsumption30Label instFuelConsumption30Label
     *
     * @return $this
     */
    public function setInstFuelConsumption30Label($instFuelConsumption30Label)
    {
        $this->container['instFuelConsumption30Label'] = $instFuelConsumption30Label;

        return $this;
    }

    /**
     * Gets instFuelConsumption40
     *
     * @return float
     */
    public function getInstFuelConsumption40()
    {
        return $this->container['instFuelConsumption40'];
    }

    /**
     * Sets instFuelConsumption40
     *
     * @param float $instFuelConsumption40 instFuelConsumption40
     *
     * @return $this
     */
    public function setInstFuelConsumption40($instFuelConsumption40)
    {
        $this->container['instFuelConsumption40'] = $instFuelConsumption40;

        return $this;
    }

    /**
     * Gets instFuelConsumption40Label
     *
     * @return \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel
     */
    public function getInstFuelConsumption40Label()
    {
        return $this->container['instFuelConsumption40Label'];
    }

    /**
     * Sets instFuelConsumption40Label
     *
     * @param \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel $instFuelConsumption40Label instFuelConsumption40Label
     *
     * @return $this
     */
    public function setInstFuelConsumption40Label($instFuelConsumption40Label)
    {
        $this->container['instFuelConsumption40Label'] = $instFuelConsumption40Label;

        return $this;
    }

    /**
     * Gets instFuelConsumption50
     *
     * @return float
     */
    public function getInstFuelConsumption50()
    {
        return $this->container['instFuelConsumption50'];
    }

    /**
     * Sets instFuelConsumption50
     *
     * @param float $instFuelConsumption50 instFuelConsumption50
     *
     * @return $this
     */
    public function setInstFuelConsumption50($instFuelConsumption50)
    {
        $this->container['instFuelConsumption50'] = $instFuelConsumption50;

        return $this;
    }

    /**
     * Gets instFuelConsumption50Label
     *
     * @return \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel
     */
    public function getInstFuelConsumption50Label()
    {
        return $this->container['instFuelConsumption50Label'];
    }

    /**
     * Sets instFuelConsumption50Label
     *
     * @param \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel $instFuelConsumption50Label instFuelConsumption50Label
     *
     * @return $this
     */
    public function setInstFuelConsumption50Label($instFuelConsumption50Label)
    {
        $this->container['instFuelConsumption50Label'] = $instFuelConsumption50Label;

        return $this;
    }

    /**
     * Gets instFuelConsumption60
     *
     * @return float
     */
    public function getInstFuelConsumption60()
    {
        return $this->container['instFuelConsumption60'];
    }

    /**
     * Sets instFuelConsumption60
     *
     * @param float $instFuelConsumption60 instFuelConsumption60
     *
     * @return $this
     */
    public function setInstFuelConsumption60($instFuelConsumption60)
    {
        $this->container['instFuelConsumption60'] = $instFuelConsumption60;

        return $this;
    }

    /**
     * Gets instFuelConsumption60Label
     *
     * @return \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel
     */
    public function getInstFuelConsumption60Label()
    {
        return $this->container['instFuelConsumption60Label'];
    }

    /**
     * Sets instFuelConsumption60Label
     *
     * @param \Psa\ConnectedCar\Model\InlineResponse2006FuelFuelTankAlerteLabel $instFuelConsumption60Label instFuelConsumption60Label
     *
     * @return $this
     */
    public function setInstFuelConsumption60Label($instFuelConsumption60Label)
    {
        $this->container['instFuelConsumption60Label'] = $instFuelConsumption60Label;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


