<?php
/**
 * InlineResponse20015
 *
 * PHP version 5
 *
 * @category Class
 * @package  Psa\ConnectedCar
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Connected Car Development
 *
 * This is the first release of our connected car API. With this API you can access more than 89 signals in a car. This API is available on Peugeot, Citroën and DS cars.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: connectedcar@mpsa.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Psa\ConnectedCar\Model;

use \ArrayAccess;
use \Psa\ConnectedCar\ObjectSerializer;

/**
 * InlineResponse20015 Class Doc Comment
 *
 * @category Class
 * @package  Psa\ConnectedCar
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20015 implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'inline_response_200_15';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'infoBeltSecurity' => '\Psa\ConnectedCar\Model\EnvironmentlistInfoDayAndNight',
        'adEmergencyBrakeSystem' => '\Psa\ConnectedCar\Model\EnvironmentlistInfoDayAndNight',
        'abs' => '\Psa\ConnectedCar\Model\EnvironmentlistInfoDayAndNight',
        'esp' => '\Psa\ConnectedCar\Model\EnvironmentlistInfoDayAndNight',
        'vin' => 'string',
        'lastUpdate' => 'string',
        'contract' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'infoBeltSecurity' => null,
        'adEmergencyBrakeSystem' => null,
        'abs' => null,
        'esp' => null,
        'vin' => null,
        'lastUpdate' => null,
        'contract' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'infoBeltSecurity' => 'infoBeltSecurity',
        'adEmergencyBrakeSystem' => 'AdEmergencyBrakeSystem',
        'abs' => 'abs',
        'esp' => 'esp',
        'vin' => 'vin',
        'lastUpdate' => 'lastUpdate',
        'contract' => 'contract'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'infoBeltSecurity' => 'setInfoBeltSecurity',
        'adEmergencyBrakeSystem' => 'setAdEmergencyBrakeSystem',
        'abs' => 'setAbs',
        'esp' => 'setEsp',
        'vin' => 'setVin',
        'lastUpdate' => 'setLastUpdate',
        'contract' => 'setContract'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'infoBeltSecurity' => 'getInfoBeltSecurity',
        'adEmergencyBrakeSystem' => 'getAdEmergencyBrakeSystem',
        'abs' => 'getAbs',
        'esp' => 'getEsp',
        'vin' => 'getVin',
        'lastUpdate' => 'getLastUpdate',
        'contract' => 'getContract'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['infoBeltSecurity'] = isset($data['infoBeltSecurity']) ? $data['infoBeltSecurity'] : null;
        $this->container['adEmergencyBrakeSystem'] = isset($data['adEmergencyBrakeSystem']) ? $data['adEmergencyBrakeSystem'] : null;
        $this->container['abs'] = isset($data['abs']) ? $data['abs'] : null;
        $this->container['esp'] = isset($data['esp']) ? $data['esp'] : null;
        $this->container['vin'] = isset($data['vin']) ? $data['vin'] : null;
        $this->container['lastUpdate'] = isset($data['lastUpdate']) ? $data['lastUpdate'] : null;
        $this->container['contract'] = isset($data['contract']) ? $data['contract'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets infoBeltSecurity
     *
     * @return \Psa\ConnectedCar\Model\EnvironmentlistInfoDayAndNight
     */
    public function getInfoBeltSecurity()
    {
        return $this->container['infoBeltSecurity'];
    }

    /**
     * Sets infoBeltSecurity
     *
     * @param \Psa\ConnectedCar\Model\EnvironmentlistInfoDayAndNight $infoBeltSecurity infoBeltSecurity
     *
     * @return $this
     */
    public function setInfoBeltSecurity($infoBeltSecurity)
    {
        $this->container['infoBeltSecurity'] = $infoBeltSecurity;

        return $this;
    }

    /**
     * Gets adEmergencyBrakeSystem
     *
     * @return \Psa\ConnectedCar\Model\EnvironmentlistInfoDayAndNight
     */
    public function getAdEmergencyBrakeSystem()
    {
        return $this->container['adEmergencyBrakeSystem'];
    }

    /**
     * Sets adEmergencyBrakeSystem
     *
     * @param \Psa\ConnectedCar\Model\EnvironmentlistInfoDayAndNight $adEmergencyBrakeSystem adEmergencyBrakeSystem
     *
     * @return $this
     */
    public function setAdEmergencyBrakeSystem($adEmergencyBrakeSystem)
    {
        $this->container['adEmergencyBrakeSystem'] = $adEmergencyBrakeSystem;

        return $this;
    }

    /**
     * Gets abs
     *
     * @return \Psa\ConnectedCar\Model\EnvironmentlistInfoDayAndNight
     */
    public function getAbs()
    {
        return $this->container['abs'];
    }

    /**
     * Sets abs
     *
     * @param \Psa\ConnectedCar\Model\EnvironmentlistInfoDayAndNight $abs abs
     *
     * @return $this
     */
    public function setAbs($abs)
    {
        $this->container['abs'] = $abs;

        return $this;
    }

    /**
     * Gets esp
     *
     * @return \Psa\ConnectedCar\Model\EnvironmentlistInfoDayAndNight
     */
    public function getEsp()
    {
        return $this->container['esp'];
    }

    /**
     * Sets esp
     *
     * @param \Psa\ConnectedCar\Model\EnvironmentlistInfoDayAndNight $esp esp
     *
     * @return $this
     */
    public function setEsp($esp)
    {
        $this->container['esp'] = $esp;

        return $this;
    }

    /**
     * Gets vin
     *
     * @return string
     */
    public function getVin()
    {
        return $this->container['vin'];
    }

    /**
     * Sets vin
     *
     * @param string $vin vin
     *
     * @return $this
     */
    public function setVin($vin)
    {
        $this->container['vin'] = $vin;

        return $this;
    }

    /**
     * Gets lastUpdate
     *
     * @return string
     */
    public function getLastUpdate()
    {
        return $this->container['lastUpdate'];
    }

    /**
     * Sets lastUpdate
     *
     * @param string $lastUpdate lastUpdate
     *
     * @return $this
     */
    public function setLastUpdate($lastUpdate)
    {
        $this->container['lastUpdate'] = $lastUpdate;

        return $this;
    }

    /**
     * Gets contract
     *
     * @return string
     */
    public function getContract()
    {
        return $this->container['contract'];
    }

    /**
     * Sets contract
     *
     * @param string $contract contract
     *
     * @return $this
     */
    public function setContract($contract)
    {
        $this->container['contract'] = $contract;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


